version: 1.0.{build}
branches:
  only:
  - feature/karma-junit
image: Visual Studio 2017
configuration: Debug
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  PATH: '%AppData%\npm;%AppData%\npm\node_modules\@angular\cli\bin;%PATH%'
  nodejs_version: 8
install:
- ps: >-
    choco install googlechrome
    Install-Product node $env:nodejs_version
    npm -g i npm@latest
    npm -g i @angular/cli@latest
    cd Etosha.Web.Api
    npm i
    cd..
before_build:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%
    dotnet restore
    cd %APPVEYOR_BUILD_FOLDER%\Etosha.Web.Api\src
    ng build --prod
build:
  project: Etosha.sln
  publish_wap: true
  parallel: true
  verbosity: minimal
test_script:
- ps: >-
    # cd %APPVEYOR_BUILD_FOLDER%\Tests\Etosha.Server.Tests
    $path = [io.path]::combine($env:APPVEYOR_BUILD_FOLDER, 'Tests\Etosha.Server.Tests')
    Set-Location -Path $path
    dotnet test
    # cd %APPVEYOR_BUILD_FOLDER%\Tests\Etosha.Web.Api.Tests
    $path = [io.path]::combine($env:APPVEYOR_BUILD_FOLDER, 'Tests\Etosha.Web.Api.Tests')
    Set-Location -Path $path
    dotnet test
    # cd %APPVEYOR_BUILD_FOLDER%\Etosha.Web.Api\src
    $path = [io.path]::combine($env:APPVEYOR_BUILD_FOLDER, 'Etosha.Web.Api\src')
    Set-Location -Path $path
    ng test --watch false --reporters=junit

after_test:
- ps: >-
    $path = [io.path]::combine($env:APPVEYOR_BUILD_FOLDER, 'Etosha.Web.Api\ng-tests')
    Set-Location -Path $path
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\ng-test-results.xml))