version: 1.0.{build}
branches:
  only:
  - develop
image: Visual Studio 2017
configuration: Debug
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  PATH: '%AppData%\npm;%AppData%\npm\node_modules\@angular\cli\bin;%PATH%'
  nodejs_version: 8
install:
- ps: choco install googlechrome -debug --ignore-checksums
- ps: Install-Product node $env:nodejs_version
- cmd: npm -g i npm@latest
- cmd: npm -g i @angular/cli@latest
- cmd: cd Etosha.Web.Api
- cmd: npm i
- cmd: cd..
before_build:
- cmd: cd %APPVEYOR_BUILD_FOLDER%
- cmd: dotnet restore
- cmd: cd %APPVEYOR_BUILD_FOLDER%\Etosha.Web.Api\src
- cmd: ng build --prod
build:
  project: Etosha.sln
  publish_wap: true
  parallel: true
  verbosity: minimal
test_script:
- ps: $path = [io.path]::combine($env:APPVEYOR_BUILD_FOLDER, 'Tests\Etosha.Server.Tests')
- ps: Set-Location -Path $path
- ps: dotnet test
- ps: $path = [io.path]::combine($env:APPVEYOR_BUILD_FOLDER, 'Tests\Etosha.Web.Api.Tests')
- ps: Set-Location -Path $path
- ps: dotnet test
- ps: $path = [io.path]::combine($env:APPVEYOR_BUILD_FOLDER, 'Etosha.Web.Api\src')
- ps: Set-Location -Path $path
- ps: ng test --watch false --reporters=junit

after_test:
- ps: $path = [io.path]::combine($env:APPVEYOR_BUILD_FOLDER, 'Etosha.Web.Api\ng-tests')
- ps: Set-Location -Path $path
- ps: Get-ChildItem -Path $path
- ps: $wc = New-Object 'System.Net.WebClient'
- ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\ng-test-results.xml))
